/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as OpengraphImageRouteImport } from './routes/opengraph-image'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LawParagraphRouteImport } from './routes/$law/$paragraph'
import { Route as ApiLawParagraphRouteImport } from './routes/api/$law/$paragraph'
import { Route as LawParagraphOpengraphImageRouteImport } from './routes/$law/$paragraph/opengraph-image'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OpengraphImageRoute = OpengraphImageRouteImport.update({
  id: '/opengraph-image',
  path: '/opengraph-image',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawParagraphRoute = LawParagraphRouteImport.update({
  id: '/$law/$paragraph',
  path: '/$law/$paragraph',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLawParagraphRoute = ApiLawParagraphRouteImport.update({
  id: '/api/$law/$paragraph',
  path: '/api/$law/$paragraph',
  getParentRoute: () => rootRouteImport,
} as any)
const LawParagraphOpengraphImageRoute =
  LawParagraphOpengraphImageRouteImport.update({
    id: '/opengraph-image',
    path: '/opengraph-image',
    getParentRoute: () => LawParagraphRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$law/$paragraph': typeof LawParagraphRouteWithChildren
  '/$law/$paragraph/opengraph-image': typeof LawParagraphOpengraphImageRoute
  '/api/$law/$paragraph': typeof ApiLawParagraphRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$law/$paragraph': typeof LawParagraphRouteWithChildren
  '/$law/$paragraph/opengraph-image': typeof LawParagraphOpengraphImageRoute
  '/api/$law/$paragraph': typeof ApiLawParagraphRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$law/$paragraph': typeof LawParagraphRouteWithChildren
  '/$law/$paragraph/opengraph-image': typeof LawParagraphOpengraphImageRoute
  '/api/$law/$paragraph': typeof ApiLawParagraphRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/opengraph-image'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$law/$paragraph'
    | '/$law/$paragraph/opengraph-image'
    | '/api/$law/$paragraph'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/opengraph-image'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$law/$paragraph'
    | '/$law/$paragraph/opengraph-image'
    | '/api/$law/$paragraph'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/opengraph-image'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$law/$paragraph'
    | '/$law/$paragraph/opengraph-image'
    | '/api/$law/$paragraph'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  OpengraphImageRoute: typeof OpengraphImageRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LawParagraphRoute: typeof LawParagraphRouteWithChildren
  ApiLawParagraphRoute: typeof ApiLawParagraphRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opengraph-image': {
      id: '/opengraph-image'
      path: '/opengraph-image'
      fullPath: '/opengraph-image'
      preLoaderRoute: typeof OpengraphImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$law/$paragraph': {
      id: '/$law/$paragraph'
      path: '/$law/$paragraph'
      fullPath: '/$law/$paragraph'
      preLoaderRoute: typeof LawParagraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$law/$paragraph': {
      id: '/api/$law/$paragraph'
      path: '/api/$law/$paragraph'
      fullPath: '/api/$law/$paragraph'
      preLoaderRoute: typeof ApiLawParagraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$law/$paragraph/opengraph-image': {
      id: '/$law/$paragraph/opengraph-image'
      path: '/opengraph-image'
      fullPath: '/$law/$paragraph/opengraph-image'
      preLoaderRoute: typeof LawParagraphOpengraphImageRouteImport
      parentRoute: typeof LawParagraphRoute
    }
  }
}

interface LawParagraphRouteChildren {
  LawParagraphOpengraphImageRoute: typeof LawParagraphOpengraphImageRoute
}

const LawParagraphRouteChildren: LawParagraphRouteChildren = {
  LawParagraphOpengraphImageRoute: LawParagraphOpengraphImageRoute,
}

const LawParagraphRouteWithChildren = LawParagraphRoute._addFileChildren(
  LawParagraphRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  OpengraphImageRoute: OpengraphImageRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LawParagraphRoute: LawParagraphRouteWithChildren,
  ApiLawParagraphRoute: ApiLawParagraphRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
